<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DailyChallenge extends Model
{
    protected $fillable = [
        'title', 
        'description', 
        'type', 
        'target_count', 
        'xp_reward', 
        'date', 
        'is_active',
        'is_auto_generated',
        'is_daily_pool',
        'weight'
    ];

    protected $casts = [
        'date' => 'date',
        'is_auto_generated' => 'boolean',
        'is_daily_pool' => 'boolean',
    ];

    public function userChallenges()
    {
        return $this->hasMany(UserChallenge::class);
    }

    // Scope untuk challenge hari ini
    public function scopeToday($query)
    {
        return $query->where('date', today())->where('is_active', true);
    }

    // Scope untuk challenge auto generated
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    // Scope untuk challenge dalam daily pool
    public function scopeDailyPool($query)
    {
        return $query->where('is_daily_pool', true);
    }

    // Scope random dengan weight
    public function scopeWeightedRandom($query, $limit = 3)
    {
        return $query->inRandomOrder()->limit($limit);
    }
}